### PR TITLE
Use self.u_kn when verbose=True in MBAR

### LINKED ISSUE #538: Verbose=True with MBAR results in an error for alternative input types of u_kn
A small improvement in consistency within pymbar would improve usability in alchemlyb.

### Backgound
Although the input, u_kn, for MBAR is defined to be a np.ndarray, it is converted to an array in line 239 with:
`        self.u_kn = np.array(u_kn, dtype=np.float64)`
Packages (i.e., alchemlyb) then instead will pass a pd.DataFrame and find that all works as expected due to this conversion.

### Problem
When `MBAR.fit(verbose=True)` is used, there is an indexing error if the provided u_kn is a pd.DataFrame. This is because of line 296:
`                    uzero = u_kn[k, indices] - u_kn[l, indices]`
where u_kn is used instead of self.u_kn.

### Solution
If `self.u_kn` were used in this line instead of `u_kn`, the users of alchemlyb would be able to benefit from the option, `verbose=True`.

### PR DESCRIPTION
**Pull request by jaclark5**
Resolves #538

Line 296 of mbar.py is changed from:
`                    uzero = u_kn[k, indices] - u_kn[l, indices]`
to
`                    uzero = self.u_kn[k, indices] - self.u_kn[l, indices]`

### CODE REVIEW

**Comment by mikemhenry** [comment]
@jaclark5 Can you add a test that does the behavior you mention in #538 That will help us prevent any regressions in the future (and might catch some edge case where the numpy array vrs pandas data frame issue crops up)

**Comment by mrshirts** [comment]
There are some weird cases where one needs either self.u_kn or a copy of it, but this should be totally fine because its just doing some analysis of whether the states are the same or not, not manipulating anything.

**Comment by jaclark5** [comment]
> @jaclark5 Can you add a test that does the behavior you mention in #538 That will help us prevent any regressions in the future (and might catch some edge case where the numpy array vrs pandas data frame issue crops up)

Sure, can you help me picture what that would look like? Since `MBAR.fit()` sets `self.u_kn = np.array(u_kn, float)` I don't foresee a similar issue unless one changes the `MBAR.fit()` method, as u_kn will be lost and only the attribute, `MBAR.u_nk` will be pertinent to other methods.

**Comment by mikemhenry** [comment]
@jaclark5 you are right!

**Review by mikemhenry — APPROVED** [review]

**Comment by mikemhenry** [comment]
The linting errors are happening on master, so this one is good to merge in!

**Pull request merged**
