### PR TITLE
Clean out old Omnia references for Pymbar 4.0 branch

### PR DESCRIPTION
**Pull request by Lnaden**
Second half of #404

### CODE REVIEW

**Comment by Lnaden** [comment]
Well. Black is just going to be difficult. OS, version, and even same-os dependent. Just going to merge this, we'll clean up black later.

**Comment by jaimergp** [comment]
The README also needs the same treatment I think!

**Comment by Lnaden** [comment]
I did? https://github.com/choderalab/pymbar/pull/412/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by jaimergp** [comment]
Oops, sorry, my bad! I was looking at the wrong branch!

**Pull request merged**
