### PR TITLE
Check out pymbar-datasets before nosetests

### PR DESCRIPTION
**Pull request by jchodera**
This addresses #243 for the automated travis tests, though I'm not sure if they will complete in the time allotted by travis.

I'll add some documentation on checking out the large datasets for local testing.

### CODE REVIEW

**Comment by jchodera** [comment]
It looks like [`test_mbar.py`](https://github.com/choderalab/pymbar/blob/master/pymbar/tests/test_mbar.py#L81) uses a test criteria that looks to see whether any estimates are more than 3 standard errors from their analytical or numerical estimates. I've changed this to 6 standard errors, but we should further correct this my the number of tests in the suite and the expected number of total commits for the lifetime of the project to not have false positives show up all the time.

**Comment by jchodera** [comment]
We might be able to use [travis caching](https://docs.travis-ci.com/user/caching/) speed up the retrieval of these large datasets.

**Comment by jchodera** [comment]
@mrshirts : Where does all the stuff in http://github.com/choderalab/pymbar-datasets even come from? It's a total and complete mess right now, and the idea of using HDF5 files to store the matrices is pretty much unworkable due to the size of these files (`gas-properties` is over 200 MB, which exceeds the strict github 100MB file size limit). Is there even any value to this?

If nobody is stepping forward to maintain this, I am going to completely purge it.

**Comment by jchodera** [comment]
Closing this in favor of #250.

**Comment by mrshirts** [comment]
They are all examples that people were having trouble with that we eventually fixed, and they contributed their data because we asked them to, so we could have a database of actual use cases for MBAR (as opposed to idealized ones).

1. gas-properties sourcing is in the README - it's a nice 2D example of various physical properties computed as a function of pressure and temperature. It if of value because it's actually how people are using MBAR.   See: For examples of the full application of property prediction, see:
  
"Force field comparison and thermodynamic property calculation of 
supercritical CO2 and CH4 using molecular dynamics simulations" by Cassiano G. Aimoli, 
Edward J. Maginn, and Charlles R.A. Abreu, in Fluid Phase Equilibria, 368, pp 80–90, 2014,
http://dx.doi.org/10.1016/j.fluid.2014.02.001

and 

"Thermodynamic Properties of Supercritical Mixtures of Carbon Dioxide and Methane: 
A Molecular Simulation Study" by Cassiano G. Aimoli,  Edward J. Maginn, and Charlles 
R.A. Abreu, in Journal of Chemical & Engineering Data, 59 (10), pp 3041–3054, 2014, 
http://dx.doi.org/10.1021/je500120v

2. alchemical-large-datasets are the full datasets for solvation of 3-methylindole that we've used for lots of other examples.

3. 8 proteins is an example of calculating heat capacities for associating alpha helices of large proteins that broke MBAR originally, and we needed to fix it.  Looks like a README needs to be added.

4. I have no idea what k69 is. Kyle added it.

**Pull request closed without merging**
