### PR TITLE
Removal of alchemical-analysis.py and linking to the new version

### PR DESCRIPTION
**Pull request by mrshirts**
Removal of alchemical-analysis.py and linking to the new version in the MobleyLab GitHub.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Works for me

**Comment by davidlmobley** [comment]
Likewise on this end.

**Comment by davidlmobley** [comment]
Though, @mrshirts - is there a way we can also get something to show up somewhat more prominently on the actual GitHub sites here so someone looking for it on the web can find the new location without using the README file?

**Comment by davidlmobley** [comment]
@kyleabeauchamp - do you know if there is an easy way to make it more clear where alchemical-analysis.py now is? Our paper points users here so we need some way to redirect them.

This pull request should be able to be merged except for that issue.

**Comment by jchodera** [comment]
> @kyleabeauchamp - do you know if there is an easy way to make it more clear where alchemical-analysis.py now is? Our paper points users here so we need some way to redirect them.

Ideas:
* Revise the paper?
* Add something in the README.md that says "Alchemical-analysis has been move to ...."

**Comment by mrshirts** [comment]
>
>
>    - Revise the paper?
>
>
This is a published paper, not a paper draft! That doesn't work.  Moving
alchemical-analysis into pymbar was agreed to a while back when we moved
the examples; since we've decided it's best to keep support outside, then
we need a new strategy.


>
>    - Add something in the README.md that says "Alchemical-analysis has
>    been move to ...."
>
>
The README for the alchemical-analysis folder will say this will the pull
request; David, is it enough to put in the pymbar/examples README.md, or
should we put something in the main pymbar/README.md?  David, those links
in the README.md are active, so it should just be one click away.

**Comment by kyleabeauchamp** [comment]
I think the README.md is a good place

**Comment by kyleabeauchamp** [comment]
The top-level README.md

**Comment by jchodera** [comment]
On Fri, May 1, 2015 at 12:13 PM, Michael Shirts <notifications@github.com>
wrote:

This is a published paper, not a paper draft! That doesn't work. Moving

alchemical-analysis into pymbar was agreed to a while back when we moved
> the examples; since we've decided it's best to keep support outside, then
> we need a new strategy.
>

Most people will get it through online downloads.  The online download can
be revised.

Journals are certainly going to have to deal with the "This URL has been
moved from X to Y" problem.  That certainly doesn't require peer review.

This kind of thing shouldn't be a problem.

The README for the alchemical-analysis folder will say this will the pull
> request;


Is that sentence in English?


> David, is it enough to put in the pymbar/examples README.md, or
> should we put something in the main pymbar/README.md? David, those links
> in the README.md are active, so it should just be one click away.


I think it's fine to put this statement in the main pymbar README.md for
now.

**Comment by davidlmobley** [comment]
Yes, I'd prefer the top-level README.md. I just wanted someone connected
with what's still in pymbar to say they were OK with this. :)

On Fri, May 1, 2015 at 9:13 AM, Kyle Beauchamp <notifications@github.com>
wrote:

> The top-level README.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/pymbar/pull/184#issuecomment-98168307>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
@mrshirts - do you want to go ahead and update the README.md so this can be merged?

**Comment by mrshirts** [comment]
I'll go ahead and merge this since it's just a text update.

**Pull request merged**
