### PR TITLE
Fix #427 : Add BAR compute overlap method

### LINKED ISSUE #427: Add methods to compute overlap and effective sample sizes for BAR?
@mrshirts : What do you think about adding a corresponding `computeOverlap()` method for BAR? This could help users identify when the BAR uncertainty estimate will be unreliable.

### PR DESCRIPTION
**Pull request by jchodera**
This PR also adds minimal tests for BAR, which appear to have been accidentally omitted (#429).

cc @zhang-ivy

### CODE REVIEW

**Comment by mrshirts** [comment]
Thanks for adding the tests!

I wonder if it would be best to not have to create an MBAR instance?  I believe the inside of the ( )^-1 in equation 10b in Bennett's 1976 paper is equivalent to the MBAR, and could be perhaps used instead of the overhead of MBAR?  Thoughts?

**Comment by jchodera** [comment]
> I wonder if it would be best to not have to create an MBAR instance? I believe the inside of the ( )^-1 in equation 10b in Bennett's 1976 paper is equivalent to the MBAR, and could be perhaps used instead of the overhead of MBAR? Thoughts?

My thinking was that establishing the (experimental) feature and tests is probably fine for now, and we can optimize for performance later.

I should probably add a warning that the method is experimental for now and the API may change in future. Do we have a standard warning for that already?

**Comment by jchodera** [comment]
@mrshirts : Can you review this so we can merge it and get a new version cut for @nividic and @cbayly13?

@mikemhenry can help cut a new release and update the conda-forge recipe.

**Comment by mrshirts** [comment]
Just FYI, I am looking at this, and working to trace down a small discrepancy in different definitions of overlap.

**Comment by mrshirts** [comment]
OK, I think this can go in.   A couple of thoughts:

* We probably want to think about making the BAR and MBAR interfaces more consistent.  That is later.  I'll file an issue here.
* There are some really interesting near-equalities in definitions of the overlap matrix. This is explored a bit in the section "The overlap matrix is a quantitative estimator of the phase-space overlap" in https://link.springer.com/article/10.1007/s10822-015-9840-9, which gives an relationship between "BAR" and "MBAR" ways of thinking about things which ends up not quite being an equality, but are different by a factor proportional to 1/N. The paper doesn't quite explore things enough. It appears to be related to https://github.com/choderalab/pymbar/issues/281, as the overlap integral is a key part of the variance estimates (in a complicated way, so not attempting to give the result here). 

SO, If one wants to ask the question, "Is the overlap good or bad"? then either method works great.  So if the need is to have this feature, then go ahead and merge it in.  Some research to do longer term on what the "right" way is.  Probably the one that is consistent with the uncertainty estimate.

**Review by mrshirts — APPROVED** [review]
Looks good, see comments above about what BAR overlap actually means.

**Comment by jchodera** [comment]
> We probably want to think about making the BAR and MBAR interfaces more consistent. That is later. I'll file an issue here.

This might be useful, but if we really wanted consistent interfaces, the MBAR would be sufficient to cover all circumstances.

> SO, If one wants to ask the question, "Is the overlap good or bad"? then either method works great. So if the need is to have this feature, then go ahead and merge it in. Some research to do longer term on what the "right" way is. Probably the one that is consistent with the uncertainty estimate.

We do need something like this, so I'll go ahead and merge this.

Perhaps we could later add an optional `method` argument that could select the exact method used for overlap computation.

**Comment by jchodera** [comment]
@mrshirts : Would it help for this method to warn that this API is experimental before we release?

**Comment by mrshirts** [comment]
Clarify "this API". The whole MBAR API? Just BARComputeOverlap?

**Comment by jchodera** [comment]
> Clarify "this API". The whole MBAR API? Just BARComputeOverlap?

I just meant that if we wanted to unify the way in which the class is initialized, there would be no need to have a separate BAR class---the MBAR class would provide a superset of the functionality of BAR.

**Comment by mrshirts** [comment]
I think that sometimes people would have w_F and w_R, and having a BAR interface would be useful.  It could potentially be MBAR under the hood, though on the other hand IIRC the BAR solver is more numerically stable.

**Comment by jchodera** [comment]
> I think that sometimes people would have w_F and w_R, and having a BAR interface would be useful. It could potentially be MBAR under the hood, though on the other hand IIRC the BAR solver is more numerically stable.

@mrshirts : Let's open a new issue to discuss those API extensions.

@mikemhenry : Can you add a warning to the `BARoverlap` method like "Warning: This API is experimental and subject to change in future releases"? Then we can cut a release!

**Comment by nividic** [comment]
@jchodera Thank you so much to get these changes in. @mikemhenry we are really hoping to incorporates this in our analyses asap. We do not mind if the API will change in the future; it is an inconvenience that we can address later. Please let us know when a release is cut with this feature in

**Comment by mikemhenry** [comment]
@nividic will do! In the meantime, you can install from source to get these changes now with `python -m pip install git+https://github.com/choderalab/pymbar.git`

**Pull request merged**
