### PR TITLE
Black

### PR DESCRIPTION
**Pull request by jaimergp**
Command run:

```
$ black --version
black, version 19.10b0

$ black -l 99 pymbar/
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/__init__.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/exp.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/tests/test_covariance.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/tests/test_bar.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/tests/test_exp.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/bar.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/tests/test_mbar_solvers.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/mbar_solvers.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/confidenceintervals.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/testsystems/__init__.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/tests/test_timeseries.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/testsystems/gaussian_work.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/testsystems/exponential_distributions.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/tests/test_utils.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/testsystems/harmonic_oscillators.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/tests/test_mbar.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/utils_for_testing.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/utils.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/tests/test_pmf.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/mbar.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/timeseries.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/pmf.py
reformatted /home/jaime/devel/py/choderalab/pymbar/pymbar/old_mbar.py
All done! ✨ 🍰 ✨
23 files reformatted, 2 files left unchanged.
```

### CODE REVIEW

**Comment by jaimergp** [comment]
Same here. `codecov` scores don't make much sense!

I did fix `ArithmaticError` -> `ArithmeticError`, but why would that change the diff? The rest of the changes is literally whitespace.

**Comment by mrshirts** [comment]
@Lnaden, @jaimergp if you can figure out why the Codecov tests are failing and and address that, I think this good to merge.

@jaimergp I think the todo from this is to make sure you have a list of name changes, and propose a PR to add to 3.0.x that deprecates the old names and tells people the new names for 4.0.

**Comment by jaimergp** [comment]
I don't fully understand the difference between both scores in codecov. We have only applied `black`? So the code is virtually the same (they compare ASTs before and after execution to guarantee they are equivalent!).

Anyway, maybe this should the last thing we merge to `pymbar4`. Otherwise there is going to be a lot of conflicting files. I would also suggest using something like https://github.com/cclauss/autoblack to apply it  automatically on every PR.

**Comment by Lnaden** [comment]
I would not worry about the codecov failures right now, we're doing so much adjustment that we can circle back to it. So long as the CI tests pass, I think its okay for now

**Comment by mrshirts** [comment]
I think that we are at a reasonable "not changing too much code this week" place, so I would go ahead and make formatting changes sooner rathe than later

**Comment by jaimergp** [comment]
The problem we have now is that we applied to `black` before some more changes were merged to `pymbar4`, so now we have these conflicting files. This will happen again as we change more things, so I'd rather run `black` only once (or have everybody involved run `black` automatically on file save in their IDE?).

**Comment by jaimergp** [comment]
I mean: we can close this PR and open a new one after we are finished with all changes.

**Comment by mrshirts** [comment]
> I mean: we can close this PR and open a new one after we are finished with all changes.

How about we fix the lint issues, and then apply `black` after that?  The other PRs will be easy to refactor on top of reformatted code.

**Comment by jaimergp** [comment]
Closing this one - black will be applied on a new PR once we merge the ongoing work. Otherwise it's going to be a conflict nightmare.

**Pull request closed without merging**
