### PR TITLE
getFreeEnergyDifferences now properly respects option return_theta.

### PR DESCRIPTION
**Pull request by mrshirts**
Fixes issue #226.  This had broken at least the heat capacity example.

### CODE REVIEW

**Comment by mrshirts** [comment]
Do we know why the CI tests are not working? The errors don't seem to be that related to this pull request.

**Comment by mrshirts** [comment]
OK, so accidentally added my changes to the heat capacity example to this pull request instead of creating another one.  I don't have the time to figure out how to break up the pull request, and submit as new, so for now they will just have to be reviewed together (Should be nothing controversial here, only the formatting was changed, the calculation is identical).

**Comment by jchodera** [comment]
Is @lnaden still the source gatekeeper here, or should I review and merge?

**Comment by Lnaden** [comment]
I was unaware I had that title. I can look over the code this afternoon after a couple meetings.

**Comment by mrshirts** [comment]
You did have it and were fulfilling the functions for a while. We had
decided a few months ago that we wanted to transition to Bryce managing
this, but this was the first code check-in since then.  I'll talk to Bryce
about this at journal club -- we'll see if he can set up yet, or if we need
Levi to.

**Comment by Lnaden** [comment]
It looks like the CI is failing because you changed the number of outputs from 3 to 2, so all the tests which expect 3 don't know how to handle the change. It might be better to go back to outputting `None` for the `Theta_ij` and only compute and store it if the flag is set.

**Comment by Lnaden** [comment]
I can see if I can modify the PR to keep it uniform outputs.

**Comment by Lnaden** [comment]
I have made a PR on this PR (on @mrshirts account) to clean up the outputs. Merging 2nd PR should fix this PR in about the cleanest way I could find.

**Comment by Lnaden** [comment]
It looks like the travis tests are passing. the appveyor tests threw a DLL error, not sure if that's related to the code change though.

**Comment by jchodera** [comment]
@Lnaden : I think you hold the dubious responsibility of being the official source gatekeeper at the current time, so feel free to merge if you think this is good to go!

**Comment by Lnaden** [comment]
Ah ha! Good to know. Ill give it one more pass when I get to a computer tonight and probably merge then. 

Do you know of a way to authorize me to restart CI tests issued by other users in case these off Windows issues happen again?

**Comment by jchodera** [comment]
> Do you know of a way to authorize me to restart CI tests issued by other users in case these off Windows issues happen again?

I wish I did!  Couldn't find anything from poking around on AppVeyor. Restarted them for now, though.

**Comment by jchodera** [comment]
Found something! I *think* you may be able to trigger AppVeyor rebuilds now....

**Comment by Lnaden** [comment]
Hmmm... I don't see any new options. But that is a minor issue to work out later.

This looks good. Merging

**Pull request merged**
