### PR TITLE
Getting CI working on the current default branch

### PR DESCRIPTION
**Pull request by mikemhenry**

### CODE REVIEW

**Comment by mikemhenry** [comment]
@mrshirts It looks like a precision issue/something about the test that makes it non-deterministic, since it passes for one of the jobs. Thoughts?

**Comment by mrshirts** [comment]
The sigmas from BAR and MBAR should not actually be exactly equal.  More specifically, BAR has 2 equations for asymptotic uncertainty that both converge to the same value, but approach it slightly differently for smaller N. Currently, it's using the one that is NOT exactly the same as MBAR.  See the comments in the pymbar4 version of BAR (in other_estimators.py)

So the test is too constrained.  Saying the two sigmas are the same to within 1% is fine for now.

**Comment by mikemhenry** [comment]
@mrshirts Okay I think I rewrote the test correctly https://github.com/choderalab/pymbar/pull/449/commits/40fc7a011a47b28c289f5cfabb27ad2554034470

**Comment by mikemhenry** [comment]
@mrshirts just a friendly bump to review this PR :)

**Review by mrshirts — APPROVED** [review]
I am not an expert on the testing framework, but I don't see any actual code changes that would cause problems.

**Review by jchodera — APPROVED** [review]
@mikemhenry Thanks so much for getting this working! This looks great!

After merging this, we will probably want to rename `master` to `pymbar3` or similar so we can do long-term maintenance releases on this branch. We'll also need to make sure to rename the branch in the GHA workflows that reference `master` if GitHub doesn't do this for us automagically.

**Comment by mikemhenry** [comment]
> if GitHub doesn't do this for us automagically.

It won't, but now I've updated the PR, good catch!

**Pull request merged**
