### PR TITLE
Fixed a typo in computeMultipleExpectations 

### PR DESCRIPTION
**Pull request by Lnaden**
K was initializing the diagonal matrix instead of I. Fixes issue #221

### CODE REVIEW

**Comment by Lnaden** [comment]
This looks like its failing travis due to Miniconda MD5 mismatch. @jchodera or @mrshirts would you know why that is occurring?

**Comment by jchodera** [comment]
Continuum borked their `Miniconda-latest-*` md5 hashes. Switch `devtools/travis-ci/install.sh` from `Miniconda-latest` to `Miniconda2-latest`.

**Comment by Lnaden** [comment]
All tests are passing, this should be good to merge.

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
