### PR TITLE
Add deprecation warnings for camelCase names and add snake_case variants

### PR DESCRIPTION
**Pull request by jaimergp**
Addresses #365 

I added a temporary `_deprecate` function in `_deprecate.py` to ease the transition and avoid duplication. I have tested it with functions and should also work with methods...

I took `master` as a base, but most of the changes here won't reach Pymbar 4 (only the name replacements), and we have this excellent table here now:

```
BAR_zero                                             BARzero
BAR_zero                                             computeBARzero
BAR                                                  computeBAR
order_replicates                                     OrderReplicates
anderson_darling                                     AndersonDarling
QQ_plot                                              QQPlot
generate_confidence_intervals                        generateConfidenceIntervals
EXP_gauss                                            EXPGauss
EXP                                                  computeEXP
EXPGauss                                             computeEXPGauss
weights                                              getWeights
compute_effective_sample_number                      computeEffectiveSampleNumber
compute_overlap                                      computeOverlap
compute_free_energy_differences                      getFreeEnergyDifferences
compute_expectations_inner                           computeExpectationsInner
compute_covariance_of_sums                           computeCovarianceOfSums
compute_expectations                                 computeExpectations
compute_multiple_expectations                        computeMultipleExpectations
compute_perturbed_free_energies                      computePerturbedFreeEnergies
compute_entropy_and_enthalpy                         computeEntropyAndEnthalpy
compute_pmf                                          computePMF
statistical_inefficiency                             statisticalInefficiency
statistical_inefficiency_multiple                    statisticalInefficiencyMultiple
integrated_autocorrelation_time                      integratedAutocorrelationTime
integrated_autocorrelation_time_multiple             integratedAutocorrelationTimeMultiple
normalized_fluctuation_correlation_function          normalizedFluctuationCorrelationFunction
normalized_fluctuation_correlation_function_multiple normalizedFluctuationCorrelationFunctionMultiple
subsample_correlated_data                            subsampleCorrelatedData
detect_equilibration                                 detectEquilibration
statistical_inefficiency_fft                         statisticalInefficiency_fft
detect_equilibration_binary_search                   detectEquilibration_binary_search
```

I have only modified callables for now. Attributes (if relevant), parameters and free variables are untouched for now.

### CODE REVIEW

**Comment by mrshirts** [comment]
Approach looks good. Assuming all of the examples run, then I think this is fine to go with.  We can worry about parameter names and variable names in pymbar4 - if they change the name, they can change capitalization in variable names.

**Comment by jaimergp** [comment]
I'd like to have some unit tests running here. Should we backport the GH Actions commits so they run here too?

**Comment by mrshirts** [comment]
> I'd like to have some unit tests running here. Should we backport the GH Actions commits so they run here too?

I guess my instinct is to focus on pymbar4? When we are about to launch 4, we will backport fixed found in the process of getting pymbar4 ready.

**Comment by jaimergp** [comment]
Fine, we can wait then. But I wouldn't like to be merged without proper testing.

**Comment by mrshirts** [comment]
> without proper testing.

By proper testing, you mean of the change in names, or anything else?

**Comment by jaimergp** [comment]
I'd like to see the unit tests running in the PR as we are doing in the `pymbar4` branch.

**Comment by mrshirts** [comment]
And to be clear, if YOU want to add something, go ahead.  I just have enough things to think about for pymbar4 that I'd rather have efforts future-focused rather than past-focused.

**Comment by jaimergp** [comment]
Of course, I didn't mean somebody else had to do that. I just didn't feel comfortable merging potentially broken code to master. I'll add backport GHA CI later this week.

**Comment by Lnaden** [comment]
Whats the way you want to incorporate this into the main pymbar4 branch? Do you just want to make a PR on that branch of these changes as well and we deal with the collision later?

**Comment by jaimergp** [comment]
I was planning on a manual search/replace using that list on the first message instead of dealing with git rebasing magic? Is that a good idea?

**Comment by Lnaden** [comment]
You might be able to cherry pick the commit, but manual is fine, it will just take a conflict resolution at some point.

**Comment by Lnaden** [comment]
Question, do we want to merge this into a new branch off master called like `3.0.6` so we don't have to worry about the collision of trying to merge pymbar4 into master with all of these caveats we are carving into 3.y.z?

**Comment by jaimergp** [comment]
Hm, that's actually a good suggestion. If we don't care about nonlinear history, I am ok with that!

**Comment by Lnaden** [comment]
The only nonlinarity here is that the 3.0.6 branch will live forever since the release must always point to it. The linear history will persist in master. going from 3.0.5 -> 4

**Comment by Lnaden** [comment]
We can also do a conflict resolution PR in the `pymbar4` branch if we really want to preserve the history.

**Comment by jaimergp** [comment]
If the only price to pay to avoid the (potentially big) conflict resolution is having an immortal branch, so be it. Is it possible to delete the branch and keep the commit attached to a tag instead?

**Comment by Lnaden** [comment]
We can. So long as we tag it correctly, the commit never gets deleted, we just have to be careful. i.e. I would make the branch, cut the release when ready (which will tag it), then delete the branch on GitHub, make sure the tarball and pointer to the commit still works, then we can delete local copies.

**Comment by jaimergp** [comment]
Also addressing #408 and #409

**Comment by jaimergp** [comment]
@Lnaden can you take another look at this now? I think it's ready to be merged to `3.0_branch`.

**Comment by Lnaden** [comment]
I think this looks good. Go ahead and merge when ready.

**Comment by jaimergp** [comment]
Just remembered about https://github.com/choderalab/pymbar/issues/364#issuecomment-605650674

`computePMF` won't have an equivalent method (as in PEP8-renamed), since that functionality has moved to a different module and class, `pymbar.pmf.PMF`. Last commit addresses this corner case. However, I can't find PMF anymore in `pymbar4`. Where should I point to, @mrshirts?

**Comment by jaimergp** [comment]
Ah, I think this is the PR I was looking for: https://github.com/choderalab/pymbar/pull/397

Please double check I am right!

**Comment by mrshirts** [comment]
Yes, correct, PMF is renamed to the (more accurate FES (free energy surface))

**Comment by jaimergp** [comment]
Ok, merging for now. Thanks!

**Pull request merged**
