### PR TITLE
Solved a number of issues that avoid lost memory

### PR DESCRIPTION
**Pull request by mrshirts**
A few changes for better memory management. In very large (500 states x 1000 samples/state) case, reduced memory by about 1/2. Specific changes detailed in issue #341, but in general, removed a number of cases where arrays were duplicated needlessly.

### CODE REVIEW

**Comment by mrshirts** [comment]
Huh, I'm not sure what the issues is. My first guess was that the data was being modified some way by mbar, since now the links are better.  But doesn't look like it.

To tired tonight to finish debugging . . .

**Comment by mrshirts** [comment]
Well, it looks like the issue was the change: 

Works:

`u_kn = u_kn - u_kn.min(axis=0)`

Fails

`u_kn -= u_kn.min(axis=0)` 

I don't get it. Must have something to do with modifying the original array.  We shouln't be changing the free energies, but could change observables.  So I guess we shouldn't do that? I can see why that's an issue, if we use the SAME internal array later to compute something else.  But I didn't see a difference when I checked?  I'll have to check again.  Will figure out later.

**Comment by mrshirts** [comment]
Still need to debug a bit more, but IF we need to copy that array (and if we do, it should be done more explicitly) to preserve the inputs, we should perhaps need to consider preconditioning inside the any acceleration loops, instead of outside.

Probably the place to do it is when creating the u_kn_nonzero array, as if it is a copy, then it doesn't matter if it's altered.

**Comment by Lnaden** [comment]
I figured out why this is failing, not sure on a fix yet. 

Under this scheme, doing the `-=` operator on the call `u_kn -= u_kn.min(0)` does correctly prevent a copy, but in doing so changes the value of that array everywhere. Given the following back trace:

```
-> self.f_k = mbar_solvers.solve_mbar_for_all_states(self.u_kn, self.N_k, self.f_k, solver_protocol)
  mbar_solvers.py(556)solve_mbar_for_all_states()
-> f_k_nonzero, all_results = solve_mbar(u_kn_nonzero, N_k_nonzero,
  mbar_solvers.py(524)solve_mbar()
-> f_k_nonzero, results = solve_mbar_once(u_kn_nonzero, N_k_nonzero, f_k_nonzero, **options)
  mbar_solvers.py(436)solve_mbar_once()
-> u_kn_nonzero = precondition_u_kn(u_kn_nonzero, N_k_nonzero, f_k_nonzero)
> mbar_solvers.py(386)precondition_u_kn()
-> u_kn -= u_kn.min(axis=0)  # do not use u_kn = u_kn + X, creates new u_kn array.
```

The following pointers then exist:
1. `u_kn -= u_kn.min(axis=0) ` references the `u_kn` arg of `precondition_u_kn`
2. `precondition_u_kn` accepts the `u_kn_nonzero` reference for its `u_kn` arg
3. This is the same `u_kn_nonzero` which has been passed into `solve_mbar_once` and `solve_mbar` above it.
4. This `u_kn_nonzero` is a sliced *view* generated from `get_nonzero_states` which accepted `u_kn` 
5. This `u_kn` was passed from `mbar_solvers.solve_mbar_for_all_states(self.u_kn, ...)` in the main `MBAR` class.

Since the `u_kn` of `precondition_u_kn` function is really just a pointer to a *view* of the `self.u_kn` matrix, doing `-=` results in the `self.u_kn` matrix being changed at those values, hence why the tests fail. I suspect having the `copy=False` kwarg in the `__init__` could do very similarly unexpected things if people modify the input `u_kn` from outside the MBAR class, but I haven't tested that yet. 

I don't have a solution for this, but at least that is what is happening here.

**Comment by mrshirts** [comment]
Yes, that's the conclusion I came to, I should have documented that here, but didn't think that anyone else was looking at this issue currently. 

We do need at least two copies of u_kn - one that is passed into MBAR, and one that is internal to MBAR.  There are currently (in pymbar4) 3 copies, and I can cut it down to two (instead of 1, in this PR - the one passed in and the u_kn_nonzero array), but will need to tweak things a bit.  Was just waiting until the reformatting was done to implement that.

**Comment by mrshirts** [comment]
Closing for now, since these changes can't be done without breaking some applications, but keeping referenced in #341 which will be left open for now to document the changes.

**Pull request closed without merging**
