### PR TITLE
 Bar.py and exp.py tests

### PR DESCRIPTION
**Pull request by mrshirts**
These are adapted from test_mbar.py. Probably could be simpler, but this works.

Also includes one bug fix for bar.py caught by the tests (bad method keyword was not caught and silently returned 0.0).

Addresses #345

### CODE REVIEW

**Comment by Lnaden** [comment]
You can change the base the PR is being proposed into by using the `edit` button at the top here of GitHub, you don't have to close and re-open if you don't want to.

**Comment by mrshirts** [comment]
Looks like failures to check out the code?  Rerunning to see if that fixes it.

**Comment by mrshirts** [comment]
No, seems to be failing on checkout for some of the tests?  @Lnaden, and ideas?

**Comment by mrshirts** [comment]
OK, was some weird mis-sync in the loading.  All good now.

**Comment by Lnaden** [comment]
Yeah, that was a new one for me too. Glad to see it fixed itself.

**Pull request merged**
