### PR TITLE
make fft calls memory safe

### PR DESCRIPTION
**Pull request by smcantab**
this follows issue #168

### CODE REVIEW

**Comment by js850** [comment]
You might want to make that optional, i.e. add a keyword.  I can imagine situations where you want to repeatedly call `statisticalInefficiency_fft` with arrays of the same size.

Also, it's worth noting that this depends on the particular implementation of `sm.tsa.stattools.acf`.  If they start using the scipy version of fft, then clearing `np.fft.fftpack._fft_cache` will not help.  Maybe you should add a comment making that point.

**Comment by smcantab** [comment]
@js850 thanks, I have added a "memsafe" kwarg + documentation and a comment

**Comment by jchodera** [comment]
Thanks!  

Shouldn't we have `memsafe` set to `True` by default, so the default behavior is potentially slower but safer?

**Comment by smcantab** [comment]
I went for the safe option first, then changed my mind. I'll change it again.

**Comment by smcantab** [comment]
done

**Pull request merged**
