### PR TITLE
BAR improvements.

### PR DESCRIPTION
**Pull request by mrshirts**
Adjusted the logic for avoiding overflows to be more robust.
Simplified the function that needs to be zeroed in BARzero, and documented it better.

### CODE REVIEW

**Comment by mrshirts** [comment]
Addresses Issue #185, plus added comments and reorganization to make the code easier to read.

**Comment by wesbarnett** [comment]
I checked this out and it does solve the issue. But it does add the following warning:

    /usr/lib/python2.7/site-packages/pymbar-3.0.0.dev0-py2.7-linux-x86_64.egg/pymbar/bar.py:347: RuntimeWarning: overflow encountered in exp
  fF = 1 / (1 + np.exp(w_F + C))

**Comment by mrshirts** [comment]
OK, I see that now. Note that the uncertainties will be correct, since all +infs only show up as denominators.  I'll think tonight about the best way to avoid that error, though.

**Comment by mrshirts** [comment]
OK, check this version -- a bit of overkill avoiding overflows, but any slowdown should be pretty much irrelevant for BAR.

**Comment by wesbarnett** [comment]
Warning is eliminated. No problems with BAR now.

**Comment by jchodera** [comment]
Could we add a nosetest for this dataset or something that would trigger
the same overflow issues?

**Comment by mrshirts** [comment]
I think it would be possible. What we'd need was a sample whose energy in the new configuration overflowed exp. If we wanted to take this dataset, then it could be run with just states 9 and 10.

**Comment by jchodera** [comment]
What about just sampling harmonic oscillator test data and modifying one of the snapshot energy differences to be larger than `np.log(sys.float_info.max)`?

**Comment by kyleabeauchamp** [comment]
Is this good to merge or are we still waiting for more tests?  We should get this done soonish so we can roll out the beta release.

**Comment by mrshirts** [comment]
I would suggest we add a test for this problem as an issue and merge it.
We'd love to spend the time to do the test now, but there are a ton of
other things right now that ALSO need to get done.

**Pull request merged**
