### PR TITLE
Pymbar 4.0

### PR DESCRIPTION
**Pull request by mrshirts**
Preparing for the big merge of pymbar 4 back into master.

### CODE REVIEW

**Comment by mrshirts** [comment]
Just lint and the issue with unpopulated histograms, which #447 will solve.  

So the plan would be to merge #447, and then merge this into master, then tag it.

**Comment by mrshirts** [comment]
@mikemhenry, @Lnaden, are we ready to make the jump?

**Comment by Lnaden** [comment]
Good on my end.

**Review by mikemhenry — APPROVED** [review]

**Comment by mikemhenry** [comment]
LGTM!

**Pull request merged**
