### PR TITLE
Fix pip install issues for python 3.x

### PR DESCRIPTION
**Pull request by jchodera**
* Add 'six' to setup.py requirements
* Add travis tests for pip install

cc: https://github.com/alchemistry/alchemlyb/pull/5

### CODE REVIEW

**Comment by jchodera** [comment]
Looks like the compiled extension was causing problems for installation via pypi. It wasn't even being built for python 3.x installs anyway, so we will need to overhaul this.

**Comment by Lnaden** [comment]
Is this still a problem with the Py 3.6 PR I just pushed?

**Comment by mrshirts** [comment]
What are the issues with merging this? Do you need me to take a look?

**Comment by Lnaden** [comment]
I'm going to close this for now, I don't think this is needed with some other changes since pip seems to work fine for now.

**Pull request closed without merging**
