### PR TITLE
Issue docstring harmonic

### PR DESCRIPTION
**Pull request by jaclark5**
Remove .vscode settings and have the docstring for the HarmonicOscillator be consistent with the code.

### CODE REVIEW

**Review by mrshirts — APPROVED** [review]
This looks good to me.  Reminds me we need to do a full switch over to u_kn vs u_kln in examples . . . .

**Comment by jaclark5** [comment]
Failure due to pylint issues that are unrelated.

**Comment by mikemhenry** [comment]
Why remove `.vscode/` from `.gitignore`? It helps people from accidentally checking in files we don't want to track.

**Comment by mikemhenry** [comment]
AH! Wow okay -- so I didn't realize that we were tracking `.vscode/` in this repository (I was so confused by your response since not tracking that folder is _exactly_ what prevents your issue).

Instead of removing it from the git ignore, can you
1) add `.vscode/` back to the git ignore file
1) backup your `.vscode/` folder/settings you want for this repo
1) run `git rm -rf .vscode/`
1) commit the result
1) now you can copy your folder back into the repo and you should be able to have your custom settings + git won't ask you to add them to the repo 

That is how it should have been setup from the start -- sorry for the confusion and I am really grateful for your contribution!

**Comment by jaclark5** [comment]
@mikemhenry This PR both deletes the vscode files you were carrying in the repository and adds vscode files to gitignore to prevent this issue in the future.

**Pull request merged**
