### PR TITLE
BAR uncertainty clarified

### PR DESCRIPTION
**Pull request by mrshirts**
Explained both BAR and MBAR uncertainty estimates, and made it possible to switch to which method. Still not clear which is best, but all the necessary information is there now.
    
Also fixed printing for python3.

### CODE REVIEW

**Comment by mrshirts** [comment]
Addresses #281

**Comment by mrshirts** [comment]
Travis-ci bug was a miniconda mismatch?

+[[ da2dd466d26e33a2b1f72fdb853a8ff0 != dd54b344661560b861f86cc5ccff044b ]]
+echo 'Miniconda MD5 mismatch'
Miniconda MD5 mismatch
+exit 1

**Comment by Lnaden** [comment]
> Travis-ci bug was a miniconda mismatch?

Ugh, this again. This happens when the hosting site pushes a new version (4.4.10 in this case), which updates the links to the `latest` file that the script downloads, BUT they don't update the MD5's on the site yet. You can see that in this case the MD5 its checking from the file (right hand side) matches the 4.4.10 file. Last time this happened I just had to wait a couple days for them to fix it.

One option we could do is parse the version inside the `latest` file that we download, then do a sed parse of the site and check it against the reported MD5 of that specific version on the site. It may be more robust, but also seems like something we shouldn't have to do.

Here is the hosting site:
https://repo.continuum.io/miniconda/

**Comment by mrshirts** [comment]
Are y'all OK with merging this for now since it passes the appveyor tests? Is coverage different? I want to try to do some building on the code (adding more tests, changing the output format).

**Comment by Lnaden** [comment]
I have a workaround fix for the MD5 problem, let me get it in as part of this PR and if the tests pass then we can merge it. I should be able to have it in a few minutes

**Comment by Lnaden** [comment]
I went ahead and merged this, it looked good and the MD5 fix worked.

**Pull request merged**
