### PR TITLE
Fix divide by zero warning in pymbar3

### PR DESCRIPTION
**Pull request by zhang-ivy**
Backports some pymbar4 changes to resolve the warning. 

See [this comment](https://github.com/choderalab/pymbar/pull/448#issuecomment-1196845293) for explanation for why the warning arises in pymbar3, but not pymbar4

### CODE REVIEW

**Comment by mikemhenry** [comment]
@zhang-ivy boot strapping has been merged, after we get this PR merged in, I think we are ready for a new pymbar3 LTS release?

**Comment by zhang-ivy** [comment]
@mikemhenry : Yes, I agree!

**Comment by mrshirts** [comment]
Probably should do a bit of adjustment on the RTD manual and the docstrings, but depends on the urgency of release.

**Comment by mikemhenry** [comment]
@mrshirts are there some formatting errors? I am looking at RTD now to make sure we build the 3.0.x version.

**Comment by mrshirts** [comment]
It didn't do things like have many of the modules documented, etc. I had a todo to go in and clean things up, but have not done that yet.

**Comment by mikemhenry** [comment]
Okay I will work on the RTD fixes here https://github.com/choderalab/pymbar/pull/471 and use that PR to get things setup for our first new release on the LTS branch. 

So now back to this PR:
@mrshirts does this PR look correct?

**Review by mrshirts — APPROVED** [review]
Looks good.

**Pull request merged**
