### PR TITLE
Reduce the cost of check for duplicate states

### PR DESCRIPTION
**Pull request by mrshirts**
Reduce the cost of checking for duplicate states. Previously, all of the samples was compared, which is unnecessary; this PR has it just check the first 50 samples in all states (unless there are les than 50 total samples), which is much faster. This is almost certainly sufficient in essentially all cases. This is an optional test that only occurs with verbose on.

This could potentially be made shorter and a little faster with clever use of numpy.unique(), but it's not clear that would really help that much besides shortening the number of lines code, since with this change, the speed cost is mostly removed. numpy unique does an unnecessary sort as well.

### CODE REVIEW

**Comment by mrshirts** [comment]
For whatever reason, seem to be failing on a test_convariance test?

**Comment by Lnaden** [comment]
That looks like its happening due to a bug which was still around when we still had list returns, I think you need to do a git rebase of this from the pymbar4 branch and that will fix itself.

**Comment by mrshirts** [comment]
Thanks, tried again!

**Comment by mrshirts** [comment]
OK, works now!

**Comment by Lnaden** [comment]
As I mentioned in the review, what if we drew a random 50 indices instead of the first 50? I think it would a simple thing which adds to the robustness of the check. Would that add too much overhead for what this fixes?

**Comment by mrshirts** [comment]
I'll give it a try later today.

**Comment by mrshirts** [comment]
OK, did a version with random 50!

**Comment by mrshirts** [comment]
Based on previous approval, merging.

**Comment by Lnaden** [comment]
The coverage report should get less noisy once we merge into master. I'll see about making it quieter

> OK, did a version with random 50!

Groovy

**Pull request merged**
