### PR TITLE
Bump conda-incubator in GHA to v2

### PR DESCRIPTION
**Pull request by Lnaden**
As it says on the tin. Follow up to #410

### CODE REVIEW

**Comment by Lnaden** [comment]
So I cannot reproduce these failures locally in osx or ubuntu docker images. They are semi-stochastic on the GHA, but they always seem to fail at least one of them.

I've added some debug lines to at least print the conditions when it fails.

**Comment by mrshirts** [comment]
Failures in test_logsumexp and test_logsumexp_b look like too fine a sensitivity to rounding errors.   Not sure if there is a way to adjust that with arguments to assert_equal - maybe will need to be adjusted to assert_almost_equal?

**Comment by Lnaden** [comment]
>  maybe will need to be adjusted to assert_almost_equal?

That is what I was going to switch to, but I was more bothered by the fact I can't reproduce it locally, yet it so frequently fails on the GHA. I'm also trying to chase down the errant SVD error in the mbar solvers test.

**Comment by Lnaden** [comment]
That seems to have worked. the Black failures are odd since I dont have them locally. I'm merging this to get it in.

**Pull request merged**
